final String HOME_SCREEN="/HOME_SCREEN";
final String CAMERA_SCREEN="/CAMERA_SCREEN";
final String MEDHISTORY_SCREEN="/MEDHISTORY_SCREEN";
final String ALARMCONFIGURATION_SCREEN="/ALARMCONFIGURATION_SCREEN";
